### PR TITLE
Update base_integrator.py

### PR DESCRIPTION
**Pull request by albernsrya**

### CODE REVIEW

**Comment by gomezzz** [comment]
Could you fix the indentation on this and the other still open PRs? Then, I will merge them.

**Comment by albernsrya** [comment]
ok I'll change it if you don't mind I'll refactor and summarize the code to make it easier to read

**Comment by gomezzz** [comment]
Yes, I was thinking maybe you can accumulate your changes into one PR and get that to pass the tests? (Note that we use black for autoformatting all PRs.)

**Comment by gomezzz** [comment]
Ah also please create the PR on the develop branch. We just changed our branching model, sorry for the guidelines being out of date about this, will fix it soon :)

**Comment by albernsrya** [comment]
Okay, thank you

**Comment by gomezzz** [comment]
Became part of #88

**Pull request closed without merging**
